version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gestion_db
    environment:
      POSTGRES_DB: gestion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestion_net

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: gestion_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - gestion_net


volumes:
  postgres_data:

networks:
  gestion_net: